Unit test for mailboxer and feature test for sending message
CraftAcademy/rails_messaging_klingons pull request #2
Opened 2018-02-21 19:51 UTC by kmthorsnes

Found bug: 
Conversations_params[:body] should be Conversations_params[:message], found bug when we filled in the form.

2018-02-22 15:14 UTC, magnus-thor reviewed
The git flow does not look good, all but two commits coming from one person.

2018-02-22 15:14 UTC, magnus-thor commented on features/send_email.feature
> +    And I should see 'Your message was successfully sent!' on my screen
You are not using Given, when, then properly.  Read this https://github.com/cucumber/cucumber/wiki/Given-When-Then
and go over the steps

2018-02-22 15:14 UTC, magnus-thor commented on app/views/conversations/_form.html.erb
> +    <%= f.submit "Send Message", class: "btn btn-success"  %>
use single qoutes and remove extra whitespace

2018-02-22 15:36 UTC, tochman requested changes

2018-02-22 15:36 UTC, tochman commented on app/models/mailbox_.rb
> +end
??

2018-02-22 15:36 UTC, tochman commented on db/migrate/20180220142903_add_delivery_tracking_info_to_mailboxer_receipts.mailboxer_engine.rb
> +end
Please remove this

2018-02-22 15:36 UTC, tochman commented on features/send_email.feature
> +  in order to communicate
Please review this user story

2018-02-22 15:36 UTC, tochman commented on features/step_definitions/send_email_steps.rb
> +    User.create(user)
Please use FactoryBot

2018-02-22 15:36 UTC, tochman commented on features/step_definitions/send_email_steps.rb
> +  select(user, :from => list)
Please do not use old hash syntax

2018-02-22 15:36 UTC, tochman commented on features/step_definitions/send_email_steps.rb
> +  fill_in(element, :with => text)
Please do not use the old hash syntax

2018-02-22 15:36 UTC, tochman commented on spec/gem_spec.rb
> +      holger = described_class.new(name: 'Holger', password: 'passord123', email: 'holgeer@kalle.no')
Please use `let`.

2018-02-22 15:36 UTC, tochman commented on spec/gem_spec.rb
> +      holger = described_class.new(name: 'Holger', password: 'passord123', email: 'holgeer@kalle.no')
```
let(:kalle) {described_class.new(name: 'Kalle', password: 'passord123', email: 'kalle@kalle.no')}
```

2018-02-22 15:36 UTC, tochman commented on spec/gem_spec.rb
> +      holger = described_class.new(name: 'Holger', password: 'passord123', email: 'holgeer@kalle.no')
Rename the file to `user_spec.rb` and move to `spec/models` folder

2018-02-22 15:36 UTC, tochman commented on spec/gem_spec.rb
> +        receiver = described_class.new(name: 'Holger', password: 'passord123', email: 'holgeer@kalle.no')
Please use `let`

2018-02-22 15:36 UTC, tochman commented on spec/rails_helper.rb
> +end
Please remove comments

2018-02-22 15:36 UTC, tochman commented on spec/spec_helper.rb
> +end
Please remove the comments

2018-02-22 15:36 UTC, tochman commented on spec/gem_spec.rb
> +
Please format code in this file and remove extra lines

2018-02-22 15:36 UTC, tochman commented on Gemfile
> +  gem 'cucumber-rails', :require => false
Please don't use hash-rockets

2018-02-22 15:36 UTC, tochman commented on Gemfile
> +  gem 'cucumber-rails', :require => false
`require: false`

2018-02-22 15:36 UTC, tochman commented on app/models/mailbox_.rb
> +end
Please remove this

2018-02-22 16:23 UTC, holgertidemand commented
Refactoring done.

2018-02-22 17:15 UTC, magnus-thor commented on features/send_email.feature
> +    And I should see 'Your message was successfully sent!' on my screen
Here is the proper way to write this scenario
```
Scenario: Kalle sends a message to Holger
    Given I am logged in as 'Kalle'
    And I am on the inbox page
    When I click the 'Compose' link
    And I select 'Holger' as 'Recipients'
    And I type in 'Heia Norge' in field for 'Subject'
    And I type in 'Heia Northug' in field for 'Message'
    And I click the 'Send Message' button
    Then I should see 'Your message was successfully sent!' on my screen
```

2018-02-22 17:15 UTC, magnus-thor commented on features/send_email.feature
>      And I should see 'Heia Northug' on my screen
Go over this again and keep this in mind
```
(Given) some context
(When) some action is carried out
(Then) a particular set of observable consequences should obtain
```

2018-02-22 17:15 UTC, magnus-thor commented on features/send_email.feature
> +    And I should see 'Heia Northug' on my screen
Three scenarios were kalle has sent message to holger, this can be extracted to the background to keep this dry.

2018-02-23 09:27 UTC, magnus-thor commented on features/mailboxer.feature
> +    And I click the 'Reply' button
When

2018-02-23 09:27 UTC, magnus-thor commented on features/mailboxer.feature
> +    And I click the 'Trash' link
When

2018-02-23 09:27 UTC, magnus-thor commented on features/mailboxer.feature
> +    And I click the 'Trash' link
when

2018-02-23 09:27 UTC, magnus-thor commented on features/mailboxer.feature
> +    When I click the 'Send Message' button
And

2018-02-23 09:42 UTC, merged